--- lib/strings のユニットテスト。
local strings = require("lib.strings")

describe("strings.trim", function()
  it("前後の空白を取り除く", function()
    assert.are.equal("abc", strings.trim("  abc  "))
  end)
  it("空白のみは空文字になる", function()
    assert.are.equal("", strings.trim("   "))
  end)
  it("文字列以外(nil)はそのまま返す", function()
    assert.is_nil(strings.trim(nil))
  end)
end)

describe("strings.isBlank", function()
  it("nil は true", function()
    assert.is_true(strings.isBlank(nil))
  end)
  it("空白のみの文字列は true", function()
    assert.is_true(strings.isBlank("  \t "))
  end)
  it("内容があれば false", function()
    assert.is_false(strings.isBlank("x"))
  end)
end)

describe("strings.quote", function()
  it("ダブルクオートで囲む", function()
    assert.are.equal('"C:\\a b"', strings.quote("C:\\a b"))
  end)
end)

describe("strings.startsWith", function()
  it("接頭辞で始まれば true", function()
    assert.is_true(strings.startsWith("aseprite -b", "aseprite"))
  end)
  it("始まらなければ false", function()
    assert.is_false(strings.startsWith("-b x.ase", "aseprite"))
  end)
end)

describe("strings.splitFirstWord", function()
  it("最初の単語と残りに分割する", function()
    local first, rest = strings.splitFirstWord("aseprite -b x.ase")
    assert.are.equal("aseprite", first)
    assert.are.equal("-b x.ase", rest)
  end)
  it("単語が1つだけなら残りは空文字", function()
    local first, rest = strings.splitFirstWord("  hello  ")
    assert.are.equal("hello", first)
    assert.are.equal("", rest)
  end)
  it("空文字は \"\", \"\" を返す", function()
    local first, rest = strings.splitFirstWord("")
    assert.are.equal("", first)
    assert.are.equal("", rest)
  end)
end)
